create table pet_user(
	ID INT(5) NOT NULL AUTO_INCREMENT,
	USER_NAME  VARCHAR(55) NOT NULL UNIQUE,
	USER_PASSSSWORD  VARCHAR(55) NOT NULL,
	PRIMARY KEY(ID)
	
);

create table pets(
        ID INT(5) NOT NULL AUTO_INCREMENT,
	PET_NAME VARCHAR(55) NOT NULL,
	PET_AGE INT(2),
	PET_PLACE VARCHAR(55),
	PET_OWNERID INT(5) NULL,
	FOREIGN KEY (PET_OWNERID)
	REFERENCES PET_USER(ID)
	ON DELETE CASCADE,
	PRIMARY KEY(ID)
);
	
	

